"""Add new fields to Deck model

Revision ID: 0d978b1c5639
Revises: a6e4e136d78a
Create Date: 2025-05-16 08:34:06.536666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d978b1c5639'
down_revision = 'a6e4e136d78a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('last_studied', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('correct_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck', schema=None) as batch_op:
        batch_op.drop_column('correct_count')
        batch_op.drop_column('last_studied')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
