"""sentence added

Revision ID: 63978af87ca2
Revises: 45438fdd6efa
Create Date: 2025-05-16 14:36:20.145480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63978af87ca2'
down_revision = '45438fdd6efa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_sentence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sentence', sa.Text(), nullable=False),
    sa.Column('translation', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_sentence')
    # ### end Alembic commands ###
