"""adapt

Revision ID: d43123cd04f5
Revises: 
Create Date: 2025-05-16 16:14:44.668813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd43123cd04f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.create_index('idx_deck_id', ['deck_id'], unique=False)
        batch_op.create_index('idx_entry', ['entry'], unique=False)

    with op.batch_alter_table('wrong_word', schema=None) as batch_op:
        batch_op.create_index('idx_user_word', ['user_id', 'word_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wrong_word', schema=None) as batch_op:
        batch_op.drop_index('idx_user_word')

    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.drop_index('idx_entry')
        batch_op.drop_index('idx_deck_id')

    # ### end Alembic commands ###
